Add Performance improvement
yash244466666/vet_clinic_db pull request #8
Opened 2023-03-14 14:03 UTC by yash244466666

2023-03-14 14:52 UTC, franclobo requested changes
Hi @yash244466666 and @tonnymuchui, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/225039904-340c14b5-dcde-4176-a7ee-f1c108e3b0f4.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- All queries created ✔️ 
- Explain Analyze command used 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] There should be ✋🏽 ☝🏽  six pictures at most one before and one after creating indexes for each query, please paste the screenshots one after another to order for good comprehension for anybody who looks at your PR.
- [ ] I recommend altering 👽 the table owner to add a column email for creating the corresponding query.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 14:52 UTC, franclobo commented on schema.sql
> +CREATE INDEX visits_animal_id ON visits(animal_id);
- [ ] The planning and execution time should be shorter than before creating the index, I suggest using ASC or DESC in the id column to reduce the times for good optimization. 👍🏽

2023-03-14 14:52 UTC, franclobo commented on schema.sql
> +CREATE INDEX visits_vet_id ON visits(vet_id);
- [ ] The planning and execution time should be shorter than before creating the index, I suggest using ASC or DESC in the id column to reduce the times for good optimization. 👍🏽

2023-03-14 14:52 UTC, franclobo commented on schema.sql
> +CREATE INDEX owners_email ON owners(email);
- [ ] The planning and execution time should be shorter than before creating the index, I suggest using ASC or DESC in the id column to reduce the times for good optimization. 👍🏽

2023-03-15 06:08 UTC, yash244466666 commented
-  **Added ASC  to reduce the times for good optimization.**

![Screenshot (102)](https://user-images.githubusercontent.com/74345713/225221477-0999aea1-461d-4ea6-94de-2e6f7b74d167.png)
![Screenshot (103)](https://user-images.githubusercontent.com/74345713/225221485-4bf01678-d79c-4802-8b9d-46895ae6d0c1.png)
![Screenshot (104)](https://user-images.githubusercontent.com/74345713/225221489-67fabcc8-4847-4a29-a8ac-aa0a1e383c25.png)

2023-03-15 08:12 UTC, arslanbisharat commented
Hi @yash244466666,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 08:15 UTC, merged